Link against Xcursor on Linux
It is at least required on Mageia 5 where I get:

Linking CXX executable Nooskewl_Runner
libNooskewl_Engine.so: undefined reference to "XcursorImageLoadCursor"
libNooskewl_Engine.so: undefined reference to "XcursorImageCreate"
libNooskewl_Engine.so: undefined reference to "XcursorImageDestroy"

I also had the same issue with the runner binary from itch.io
(though this time the issue was directly "undefined symbol")